export const acciones = [
  { value: 1, label: "NO CONTESTA" },
  { value: 2, label: "OCUPADO" },
  { value: 3, label: "NO SE ENCUENTRA" },
  { value: 4, label: "NUMERO EQUIVOCADO" },
  { value: 5, label: "FUERA DE SERVICIO" },
  { value: 6, label: "NO VIVE AHI" },
  { value: 7, label: "COMPROMISO DE PAGO" },
  { value: 8, label: "NO PAGA" },
  { value: 9, label: "CUOTA AL DIA" },
  { value: 10, label: "NOTIFICACION EN MANO" },
  { value: 13, label: "CARTERA ROJA" },
  { value: 14, label: "SOCIO FALLECIDO" },
  { value: 15, label: "RECORDATORIO DE PAGO" },
  { value: 18, label: "COMP. PAGO EFECTIVO" },
  { value: 19, label: "COMP. PAGO NO EFECTIVO" },
  { value: 20, label: "DOMICILIO INEXISTENTE" },
  { value: 21, label: "NOTIFICACION BAJO PUERTA" },
];

export const nueavaaccion = [
  { value: 22, label: "LLAMAR DE NUEVO" },
  { value: 11, label: "SE ENVIA COBRADOR" },
  { value: 12, label: "PASA POR OFICINA" },
  { value: 16, label: "DEBITO" },
  { value: 17, label: "CREDITO" },
  { value: 23, label: "CASO CERRADO" },
];

export const sucursales = [
  { value: 1, label: "CASA CENTRAL" },
  { value: 3, label: "PALPALA" },
  { value: 5, label: "PERICO" },
  { value: 60, label: "SAN PEDRO" },
];

export const meses = [
  { value: 1, label: "ENERO" },
  { value: 2, label: "FEBRERO" },
  { value: 3, label: "MARZO" },
  { value: 4, label: "ABRIL" },
  { value: 5, label: "MAYO" },
  { value: 6, label: "JUNIO" },
  { value: 7, label: "JULIO" },
  { value: 8, label: "AGOSTO" },
  { value: 9, label: "SEPTIEMBRE" },
  { value: 10, label: "OCTUBRE" },
  { value: 11, label: "NOVIEMBRE" },
  { value: 12, label: "DICIEMBRE" },
];

export const meses2 = [
  { value: "01", label: "ENERO" },
  { value: "02", label: "FEBRERO" },
  { value: "03", label: "MARZO" },
  { value: "04", label: "ABRIL" },
  { value: "05", label: "MAYO" },
  { value: "06", label: "JUNIO" },
  { value: "07", label: "JULIO" },
  { value: "08", label: "AGOSTO" },
  { value: "09", label: "SEPTIEMBRE" },
  { value: "10", label: "OCTUBRE" },
  { value: "11", label: "NOVIEMBRE" },
  { value: "12", label: "DICIEMBRE" },
];

export const meses3 = [
  { value: 1, label: "01" },
  { value: 2, label: "02" },
  { value: 3, label: "03" },
  { value: 4, label: "04" },
  { value: 5, label: "05" },
  { value: 6, label: "06" },
  { value: 7, label: "07" },
  { value: 8, label: "08" },
  { value: 9, label: "09" },
  { value: 10, label: "10" },
  { value: 11, label: "11" },
  { value: 12, label: "12" },
];

export const mesventas = [
  { value: "ENERO", label: "ENERO" },
  { value: "FEBRERO", label: "FEBRERO" },
  { value: "MARZO", label: "MARZO" },
  { value: "ABRIL", label: "ABRIL" },
  { value: "MAYO", label: "MAYO" },
  { value: "JUNIO", label: "JUNIO" },
  { value: "JULIO", label: "JULIO" },
  { value: "AGOSTO", label: "AGOSTO" },
  { value: "SEPTIEMBRE", label: "SEPTIEMBRE" },
  { value: "OCTUBRE", label: "OCTUBRE" },
  { value: "NOVIEMBRE", label: "NOVIEMBRE" },
  { value: "DICIEMBRE", label: "DICIEMBRE" },
];

export const anosventas = [
  { value: 2017, label: "2017" },
  { value: 2018, label: "2018" },
  { value: 2019, label: "2019" },
  { value: 2020, label: "2020" },
  { value: 2021, label: "2021" },
  { value: 2022, label: "2022" },
  { value: 2023, label: "2023" },
  { value: 2024, label: "2024" },
  { value: 2025, label: "2025" },
];

export const anos = [
  { value: 2020, label: "2020" },
  { value: 2021, label: "2021" },
  { value: 2022, label: "2022" },
  { value: 2023, label: "2023" },
  { value: 2024, label: "2024" },
  { value: 2025, label: "2025" },
  { value: 2026, label: "2026" },
  { value: 2027, label: "2027" },
  { value: 2028, label: "2028" },
  { value: 2029, label: "2029" },
  { value: 2030, label: "2030" },
];

export const conceptossep = [
  { value: 1, label: "Alquiler de Sala Velatoria" },
  { value: 2, label: "Alquiler Sala Velatoria" },
  { value: 3, label: "Anticipo de Clientes" },
  { value: 4, label: "Ataudes Comprados" },
  { value: 5, label: "Avisos Funebres" },
  { value: 6, label: "Changas de sepelio (Atención sala Velatoria)" },
  { value: 7, label: "Combustibles Sepelio" },
  { value: 8, label: "Comida de Sepelio" },
  { value: 9, label: "Compra de Estaño - Formol" },
  { value: 10, label: "Corona Floral" },
  { value: 11, label: "Cremación" },
  { value: 12, label: "Cremación" },
  { value: 13, label: "Gasto Set - Cafetería" },
  {
    value: 14,
    label:
      "Gastos de Traslados por Servicio Calle Provincial - Hasta 60km por Servicio",
  },
  { value: 15, label: "golosinas" },
  { value: 16, label: "Habilitacion Tesoreria" },
  { value: 17, label: "Impuestos Municipales" },
  { value: 18, label: "LIMSA Sala Velatoria" },
  { value: 19, label: "Mantenimiento de Capilla y Sala" },
  { value: 20, label: "Mejora de Ataud" },
  { value: 21, label: "Movilidad" },
  { value: 22, label: "Pago de Guardia Nocturna" },
  { value: 23, label: "Subsidio de Luto" },
  { value: 24, label: "Subsidio de Luto Extraordinario" },
  { value: 25, label: "Valores a Depositar" },
  { value: 26, label: "Venta de Servicio de Sepelio Particular" },
  { value: 27, label: "Ventas de Traslados" },
];

export const empresa = [
  { value: 1, label: "WERCHOW S.A." },
  { value: 2, label: "WERCHOW S.R.L." },
];

export const porciva = [
  { value: 1, label: "IVA 21%" },
  { value: 2, label: "IVA 10,5%" },
];

export const prov = [
  { value: 1, label: "E.J.E.S.A." },
  { value: 2, label: "LIMSA" },
  { value: 3, label: "Pepe" },
  { value: 4, label: "Alejandro Cazon" },
  { value: 5, label: "Lopez Alejandro" },
  { value: 6, label: "movilidad" },
  { value: 7, label: "FERRETERIA URQUIZA" },
  { value: 8, label: "3A PROPIEDADES" },
  { value: 9, label: "Jorge Uro" },
  { value: 10, label: "DIRECCION PROVINCIAL DE RENTAS" },
  { value: 11, label: "BANDUR PABLO" },
  { value: 12, label: "GARECA ABEL" },
  { value: 13, label: "ALVARO RUEDA" },
  { value: 14, label: "VALDA CARLOS" },
  { value: 15, label: "ESTACIONAMIENTO VS" },
  { value: 16, label: "EL HORNERO " },
  { value: 17, label: "WERCHOW" },
  { value: 18, label: "SANTIAGO J. IRIARTE" },
  { value: 19, label: "JOAQUIN IRIARTE" },
  { value: 20, label: "FERMIN IRIARTE" },
  { value: 21, label: "BCO ICBC CAJA SEGURIDAD" },
  { value: 22, label: "Sepelios Generico" },
  { value: 23, label: "ELECTROCENTER" },
  { value: 24, label: "HECCAR" },
  { value: 25, label: "ANSARDI" },
  { value: 26, label: "FIORI" },
  { value: 27, label: "LOPEZ CANFORA" },
  { value: 28, label: "sigma srl" },
  { value: 29, label: "las lomas srl" },
  { value: 30, label: "lubricentro stop car" },
  { value: 31, label: "casa limpia" },
  { value: 32, label: "Carrefour" },
  { value: 33, label: "Rodof Materiales" },
  { value: 34, label: "Farmacia de la Salud" },
  { value: 35, label: "Gomeria El Auxilio" },
  { value: 36, label: "GC Materiales" },
  { value: 37, label: "panaderia pan de azucar" },
  { value: 38, label: "municipalidad de ss de jujuy" },
  { value: 39, label: "dergam" },
  { value: 40, label: "hostal andino" },
  { value: 41, label: "el unquillar hotel" },
  { value: 42, label: "el mordisco napolitana" },
  { value: 43, label: "cavirama" },
  { value: 44, label: "toba s. r .l" },
  { value: 45, label: "minimercadito rulito" },
  { value: 46, label: "comodin 3" },
  { value: 47, label: "ypf la madrid" },
  { value: 48, label: "distrifarma" },
  { value: 49, label: "MINIMERCADITO LA CHABEL" },
  { value: 50, label: "mebac" },
  { value: 51, label: "restaurat elisa" },
  { value: 52, label: "esso los perales" },
  { value: 53, label: "babnik s.a" },
  { value: 54, label: "REFINOR" },
  { value: 55, label: "despensa granel granel" },
  { value: 56, label: "milenium srl" },
  { value: 57, label: "refinor la rotonda" },
  { value: 58, label: "electromecanica jujuy" },
  { value: 59, label: "RTV PIOLI" },
  { value: 60, label: "LA RABIOLA" },
  { value: 61, label: "DESPENSA PATRY" },
  { value: 62, label: "papelera cotillon felices fiestas" },
  { value: 63, label: "despensa y verduleria vicios" },
  { value: 64, label: "despensa el antigal" },
  { value: 65, label: "CORRALOS LUKAS" },
  { value: 66, label: "ESTACION DE SERVICIO TINKU" },
  { value: 67, label: "despensa rodriguez" },
  { value: 68, label: "cia petrolera palpala srl" },
  { value: 69, label: "andina s.a" },
  { value: 70, label: "municipalidad de palpala" },
  { value: 71, label: "pussetto salta s.a" },
  { value: 72, label: "friuli srl" },
  { value: 73, label: "LIBRERIA SAN  PABLO" },
  { value: 74, label: "lubricentro gasimovil" },
  { value: 75, label: "la nueva ciudad" },
  { value: 76, label: "Despensa Pepe" },
  { value: 77, label: "farmacity s.a" },
  { value: 78, label: "maderera vito" },
  { value: 79, label: "estacion miguel angel alvarez" },
  { value: 80, label: "Farmacia Avenida" },
  { value: 81, label: "168 MARKET JUJUY II" },
  { value: 82, label: "Rotiseria Don Vilca" },
  { value: 83, label: "PINTURERIAS MARTIN" },
  { value: 84, label: "EMPANADERIA OHMAYRA" },
  { value: 85, label: "jujuy materiales" },
  { value: 86, label: "itati lubripartes" },
  { value: 87, label: "brumafra srl" },
  { value: 88, label: "estac de serv ruta 34" },
  { value: 89, label: "monica isabel vilca" },
  { value: 90, label: " 7 minutos" },
  { value: 91, label: "eli comestibles" },
  { value: 92, label: "con sabor a mi" },
  { value: 93, label: "geminis s.a" },
  { value: 94, label: "la gran empanada" },
  { value: 95, label: "panificadora artepan" },
  { value: 96, label: "la casa del peugeot" },
  { value: 97, label: "minimercadito ansa" },
  { value: 98, label: "farmacia norte" },
  { value: 99, label: "R&G SERVICE" },
  { value: 100, label: "BONAFIDE" },
  { value: 101, label: "PAPELERA LA NUEVA TERMINAL" },
  { value: 102, label: "COMEDOR LA CABAÑA" },
  { value: 103, label: "MINIMERCADITO EL EXODO" },
  { value: 104, label: "al vi lubriservice" },
  { value: 105, label: "despensa los helechos" },
  { value: 106, label: "minimercadito rodrigo" },
  { value: 107, label: "despensa yanina" },
  { value: 108, label: "estacion de serv ypf cayo lorenza" },
  { value: 109, label: "el humahuaqueño" },
  { value: 110, label: "alte brown neumaticos" },
  { value: 111, label: "bondi srl" },
  { value: 112, label: "MUNICIPALIDAD DE SAN PEDRO DE JUJUY" },
  { value: 113, label: "maxima limpieza" },
  { value: 114, label: "maxi kiosco mateo" },
  { value: 115, label: "plazoleta srl" },
  { value: 116, label: "despensa mariaca" },
  { value: 117, label: "drugstore dulce passion" },
  { value: 118, label: "el lobito repuestos" },
  { value: 119, label: "la cerrajeria del automotor del norte" },
  { value: 120, label: "aeropuerto jujuy" },
  { value: 121, label: "rotiseria la tia" },
  { value: 122, label: "kiosco belen" },
  { value: 123, label: "cc .ss Refinor" },
  { value: 124, label: "bar restaurant juancito" },
  { value: 125, label: "glasser" },
  { value: 126, label: "farmacias farmar jujuy" },
  { value: 127, label: "villena juan oscar" },
  { value: 128, label: "comadre anita" },
  { value: 129, label: "municipalidad de perico" },
  { value: 130, label: "c.a.t.e" },
  { value: 131, label: "vineria don santiago" },
  { value: 132, label: "punto medio" },
  { value: 133, label: "s.a producciones" },
  { value: 134, label: "al paso sandwicheria" },
  { value: 135, label: "corralon isaac" },
  { value: 136, label: "FIAMBRERIA LA GRANJA DE SANTIAGO" },
  { value: 137, label: "sandwicheria nico" },
  { value: 138, label: "FIAMBRERIA LOS CUMPITA" },
  { value: 139, label: "DESPENSA GABY" },
  { value: 140, label: "AUTOSERVICIO BUEN GUSTO" },
  { value: 141, label: "DESPENSA LILI" },
  { value: 142, label: "libreria magisterio" },
  { value: 143, label: "escapes legui" },
  { value: 144, label: "refinor v.m.m" },
  { value: 145, label: "municipalidad del carmen" },
  { value: 146, label: "TALLER FUTURO" },
  { value: 147, label: "pinturerias exodo" },
  { value: 148, label: "despensa santiago" },
  { value: 149, label: "FARMACIA SAN JAVIER" },
  { value: 150, label: "farmacia belgrano" },
  { value: 151, label: "fiambreria la sabrosita" },
  { value: 152, label: "SIRVIÑACU COMIDAS I MUSICA" },
  { value: 153, label: "BLASCO CAROLINA MARIA MARCELA" },
  { value: 154, label: "rotiseria avenida" },
  { value: 155, label: "estacion de servicio los lapachos" },
  { value: 156, label: "la confi" },
  { value: 157, label: "hostal los 7 hermanos" },
  { value: 158, label: "residencial confiteria la quiaca food service" },
  { value: 159, label: "MAR DE CRISTALES" },
  { value: 160, label: "El Jaguel SA" },
  { value: 161, label: "correo argentino" },
  { value: 162, label: "empanaderia y pizzeria aranda" },
  { value: 163, label: "despensa san martin" },
  { value: 164, label: "GREEN OPTION" },
  { value: 165, label: "todo descartable" },
  { value: 166, label: "RTP INSUMOS" },
  { value: 167, label: "WARNES REPUESTOS" },
  { value: 168, label: "la estancia" },
  { value: 169, label: "libreria y regaleria benjamin" },
  { value: 170, label: "juan pablo gonzalez cernuchi" },
  { value: 171, label: "TODO GOMA" },
  { value: 172, label: "DESPENSA MIKA" },
  { value: 173, label: "petro rey" },
  { value: 174, label: "grido helados" },
  { value: 175, label: "VARELA MATERIALES" },
  { value: 176, label: "PAÑALERA MAURITO" },
  { value: 177, label: "lalo accesorios" },
  { value: 178, label: "febbre servicios informaticos" },
  { value: 179, label: "encomineda cordoba" },
  { value: 180, label: "telecentro despensa solange" },
  { value: 181, label: "SHI ZHIXIONG" },
  { value: 182, label: "el molle" },
  { value: 183, label: "floreria cultivo luis" },
  { value: 184, label: "CASTILLO" },
  { value: 185, label: "Hotel Frontera" },
  { value: 186, label: "resto bar  LA BOCA DEL TIGRE" },
  { value: 187, label: "maria cristina falcon de gloss" },
  { value: 188, label: "sitec informatica" },
  { value: 189, label: "COPETIN DE PASO RUTA 9" },
  { value: 190, label: "MARCELA IVONE COMESTIBLES" },
  { value: 191, label: "LIBRA SRL" },
  { value: 192, label: "MAXI KIOSCO JOHANNA" },
  { value: 193, label: "corralon el progreso" },
  { value: 194, label: "pintureria ferreteria rosa larrieu" },
  { value: 195, label: "gomeri alberto" },
  { value: 196, label: "Eleganza" },
  { value: 197, label: "assef mateo daniel" },
  { value: 198, label: "selectron" },
  { value: 199, label: "maderera oasis" },
  { value: 200, label: "C0RRALON LUKAS" },
  { value: 201, label: "ANUN HERMANOS" },
  { value: 202, label: "centro de serv pompeya" },
  { value: 203, label: "PANIFICADORA SAN MARTIN" },
  { value: 204, label: "PANADERIA GRANADA" },
  { value: 205, label: "aromas y esencias" },
  { value: 206, label: "restaurant la salteña" },
  { value: 207, label: "ingenio jujeño despensa" },
  { value: 208, label: "EL FUERTE DE LAS ENPANADAS" },
  { value: 209, label: "servicios wendler" },
  { value: 210, label: "hafid autopartes" },
  { value: 211, label: "polonia z" },
  { value: 212, label: "tecno hidraulica srl" },
  { value: 213, label: "fontana diesel" },
  { value: 214, label: "minimercadito itati" },
  { value: 215, label: "DESPENSA SALDIA" },
  { value: 216, label: "FARMACIA PABLO SORIA" },
  { value: 217, label: "RESTAURANTE ROTISERIA PETRAS" },
  { value: 218, label: "empanaderia doña rosa 2" },
  { value: 219, label: "eess le park" },
  { value: 220, label: "la central papelera" },
  { value: 221, label: "comedor la tia" },
  { value: 222, label: "MERCADITO TUTTI FRUTTI" },
  { value: 223, label: "francisco mantiel sacafi" },
  { value: 224, label: "COMEDOR EL PASO" },
  { value: 225, label: "despensa senador perez" },
  { value: 226, label: "TODO PLASTICO Y MAS" },
  { value: 227, label: "chapa eme" },
  { value: 228, label: "crillon" },
  { value: 229, label: "peressin hermanos srl" },
  { value: 230, label: "fotocopiadora" },
  { value: 231, label: "restaurant wasi" },
  { value: 232, label: "fotocopiadora y kiosco gaston" },
  { value: 233, label: "despensa maxi mer" },
  { value: 234, label: "sabores" },
  { value: 235, label: "resto bar monik" },
  { value: 236, label: "ova informatica" },
  { value: 237, label: "el mundo del plomero" },
  { value: 238, label: "anibal sergio pacifico burgos" },
  { value: 239, label: "tio aquiles" },
  { value: 240, label: "aromas de la quebrada" },
  { value: 241, label: `tano's pizza bar` },
  { value: 242, label: "belind lilian esther" },
  { value: 243, label: "ITALMAC" },
  { value: 244, label: "DRUGSTORE FRIENDS" },
  { value: 245, label: "supermercado dia" },
  { value: 246, label: "Rotiseria xibi xibi" },
  { value: 247, label: "el palenque" },
  { value: 248, label: "BLACK" },
  { value: 249, label: "jose alberto gutierrez" },
  { value: 250, label: "kalapurca" },
  { value: 251, label: "LDT todo para el hogar" },
  { value: 252, label: "mi cochera y mi lavadero" },
  { value: 253, label: "manos jujeñas" },
  { value: 254, label: "COMESTIBLES ELI" },
  { value: 255, label: "comicion municipal de yala" },
  { value: 256, label: "eess ypf pozo hondo" },
  { value: 257, label: "ypf ruta 34" },
  { value: 258, label: "AZUL COMBUSTIBLES" },
  { value: 259, label: "PETROSERVICE SRL" },
  { value: 260, label: "TEJADA LUCIANO RAMIRO" },
  { value: 261, label: "el monarca" },
  { value: 262, label: "farmacia santa anita" },
  { value: 263, label: "vivas claudio marcelo" },
  { value: 264, label: "tolaba adrian ermindo" },
  { value: 265, label: "petrolera jujuy" },
  { value: 266, label: "las centerarias" },
  { value: 267, label: "gnc punto medio" },
  { value: 268, label: "GNC CENTRO " },
  { value: 269, label: "SEPERGAS GNC" },
  { value: 270, label: "FERREYRA RODOLFO ROLANDO" },
  { value: 271, label: "jujuy gnc" },
  { value: 272, label: "concecionaria norte srl" },
  { value: 273, label: "sandwicheria gabriel" },
  { value: 274, label: "GNC PREMIUM" },
  { value: 275, label: "gasari repuestos" },
  { value: 276, label: "ojeda juan pablo" },
  { value: 277, label: "durandal laura elizabeth" },
  { value: 278, label: "SUPER CARNES GOYO" },
  { value: 279, label: "sandwicheria pachamama" },
  { value: 280, label: "minimercado sergio" },
  { value: 281, label: "PAPELERA LIBERTAD" },
  { value: 282, label: "telecentro lavalle" },
  { value: 283, label: "restautar tiahuanaco" },
  { value: 284, label: "remises  san jose patrono" },
  { value: 285, label: "nutrisan srl" },
  { value: 286, label: "floreria zubiaurre" },
  { value: 287, label: "MULTILUB" },
  { value: 288, label: "libreria el salvador" },
  { value: 289, label: "rene horacio hernandez" },
  { value: 290, label: "Los Itares S.R.L" },
  { value: 291, label: "subia jose roberto" },
  { value: 292, label: "neumáticos  jujuy S.A " },
  { value: 293, label: "LA FABRICA DE PIZZAS" },
  { value: 294, label: "CENCOSUD S.A" },
  { value: 295, label: "GNC SAN FELIPE" },
  { value: 296, label: "la gauchita" },
];

export const tipofac = [
  { value: 1, label: "Factura A" },
  { value: 2, label: "Factura B" },
  { value: 3, label: "Factura C" },
  { value: 4, label: "Nota de Credito A" },
  { value: 5, label: "Nota de Credito B" },
  { value: 6, label: "Nota de Credito C" },
  { value: 7, label: "Nota de Debito A" },
  { value: 8, label: "Nota de Debito B" },
  { value: 9, label: "Nota de Debito C" },
  { value: 10, label: "Recibo A" },
  { value: 11, label: "Recibo B" },
  { value: 12, label: "Recibo C" },
  { value: 13, label: "Recibo X" },
  { value: 14, label: "Boleta Deposito" },
  { value: 15, label: "Ticket Comun" },
];

export const mediopag = [
  { value: 1, label: "Contado" },
  { value: 2, label: "A Cuenta" },
  { value: 3, label: "Banco" },
  { value: 4, label: "Tarjeta" },
];

export const operadoressep = [
  { value: "pbandur", label: "Pablo Bandur" },
  { value: "juro", label: "Jorge Uro" },
  { value: "muro", label: "Marcelo Uro" },
  { value: "mquiroz", label: "Marcelo Quiroz" },
  { value: "agareca", label: "Abel Gareca" },
  { value: "jzamorano", label: "Jose Zamorano" },
  { value: "dmesori", label: "Domingo Mesori" },
  { value: "cvalda", label: "Carlos Valda" },
];

export const operadorescamp = [
  { value: "mgalian", label: "Maria Galian" },
  { value: "ladorno", label: "Lucia Adorno" },
  { value: "mcarrizo", label: "Marisa Carrizo" },
  { value: "vgorosito", label: "Vanesa Gorosito" },
  { value: "sjuarez", label: "Silvia Juarez" },
];

export const capitalaprest = [
  { value: "1000", label: "1000" },
  { value: "1500", label: "1500" },
  { value: "2000", label: "2000" },
  { value: "2500", label: "2500" },
  { value: "3000", label: "3000" },
  { value: "4000", label: "4000" },
  { value: "5000", label: "5000" },
  { value: "6000", label: "6000" },
  { value: "8000", label: "8000" },
  { value: "10000", label: "10000" },
  { value: "12000", label: "12000" },
  { value: "15000", label: "15000" },
  { value: "20000", label: "20000" },
  { value: "30000", label: "30000" },
];

export const cuotasprest = [
  { value: "3", label: "3" },
  { value: "6", label: "6" },
  { value: "10", label: "10" },
  { value: "12", label: "12" },
];

export const renovaprest = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO" },
];

export const estadopres = [
  { value: "PENDIENTE", label: "PENDIENTE" },
  { value: "APROBADO", label: "APROBADO" },
  { value: "CANCELADO", label: "CANCELADO" },
  { value: "RECHAZADO", label: "RECHAZADO" },
];

export const estadocartera = [
  { value: 0, label: "Atrasados 1000 Cobrador" },
  { value: 1, label: "Atrasados 1000 Oficina" },
  { value: 2, label: "Atrasados Tarjetas" },
  { value: 3, label: "Atrasados Banco" },
];

export const cartera = [
  { value: 0, label: "Oficina y Cobrador" },
  { value: 1, label: "Tarjetas" },
  { value: 2, label: "Bancos" },
  { value: 3, label: "Policia" },
];

export const zonas = [
  { value: 1, label: "Oficina Casa Central" },
  { value: 3, label: "Oficina Palpala" },
  { value: 5, label: "Oficina Perico" },
  { value: 30, label: "Oficina El Carmen" },
  { value: 60, label: "Oficina San Pedro" },
];

export const zonaPal = [{ value: 3, label: "Oficina Palpala" }];

export const zonaPer = [{ value: 5, label: "Oficina Perico" }];

export const zonaSP = [{ value: 60, label: "Oficina San Pedro" }];

export const zonaCC = [{ value: 1, label: "Oficina Casa Central" }];
